export enum NotificationType {
  RESERVATION_REQUEST_CREATED = 'RESERVATION_REQUEST_CREATED',
  RESERVATION_REQUEST_RESPONDED = 'RESERVATION_REQUEST_RESPONDED',
  RESERVATION_CANCELLED = 'RESERVATION_CANCELLED',
  HOST_RATED = 'HOST_RATED',
  ACCOMMODATION_RATED = 'ACCOMMODATION_RATED',
}

export const HOST_NOTIFICATION_TYPES = [
  NotificationType.RESERVATION_REQUEST_CREATED,
  NotificationType.RESERVATION_CANCELLED,
  NotificationType.HOST_RATED,
  NotificationType.ACCOMMODATION_RATED,
];

export const GUEST_NOTIFICATION_TYPES = [
  NotificationType.RESERVATION_REQUEST_RESPONDED,
];
