syntax = "proto3";

package reservation;

service ReservationService {
  rpc GetReservationForRating (RatingValidationRequest) returns (RatingValidationResponse);
  rpc HasActiveOrFutureReservations (HasActiveReservationsRequest) returns (HasActiveReservationsResponse);
}

message RatingValidationRequest {
  string reservationId = 1;
  string guestId = 2;
}

message RatingValidationResponse {
  bool canRate = 1;
  string hostId = 2;
  string accommodationId = 3;
  bool isPast = 4;
}

message HasActiveReservationsRequest {
  string userId     = 1;  
  bool   isHostCheck = 2; 
}

message HasActiveReservationsResponse {
  bool   hasActiveOrFuture = 1;
  string message           = 2; 
}
